version: "3.9"
services:
    web:
        build: ./docker/web
        working_dir: /app
        user: application
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/app
        tmpfs:
          - /tmp:mode=1777
        environment:
          - WEB_DOCUMENT_ROOT=/app
          - PHP_DISPLAY_ERRORS=1